---
abstract: 'Yet another HTTP useragent string parser.'
author:
  - 'Takaaki Mizuno <cpan@takaaki.info>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-DetectUserAgent
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor: 0
  Test::Base: 0
  Test::More: 0
  version: 0
resources:
  repository: https://github.com/neilbowers/HTTP-DetectUserAgent
version: 0.03
